apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Beispiel
  template:
    metadata:
      labels:
        app: Beispiel
    spec:
      containers:
      - name: containerapp
        image: kubedevio/nginx-color:green
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

